A_CDR1:
  A_CDR1: ca_kpca_cosine
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
A_CDR1A_CDR2A_CDR3:
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
A_CDR1A_CDR2A_CDR3B_CDR1B_CDR2B_CDR3:
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
A_CDR2:
  A_CDR2: ca_kpca_cosine
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
A_CDR3:
  A_CDR3: ca_kpca_cosine
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
A_variable:
  A_variable: ca_kpca_cosine
B_CDR1:
  A_variable: ca_kpca_cosine
  B_CDR1: ca_kpca_cosine
  B_variable: ca_kpca_cosine
B_CDR1B_CDR2B_CDR3:
  A_variable: ca_kpca_cosine
  B_variable: ca_kpca_cosine
B_CDR2:
  A_variable: ca_kpca_cosine
  B_CDR2: ca_kpca_cosine
  B_variable: ca_kpca_cosine
B_CDR3:
  A_variable: ca_kpca_cosine
  B_CDR3: ca_kpca_cosine
  B_variable: ca_kpca_cosine
B_variable:
  B_variable: ca_kpca_cosine
